enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "ember-source@*":
    dependencies:
      "@babel/core": "*"
  "ember-cli-typescript@*":
    dependencies:
      "@babel/core": "*"
  "ember-cli-babel@*":
    dependencies:
      "@babel/core": "*"
  "@ember-data/private-build-infra@*":
    dependencies:
      "@babel/core": "*"
  "ember-resolver@*":
    dependencies:
      "@babel/core": "*"
  "ember-compatibility-helpers@*":
    dependencies:
      "@babel/core": "*"

