enableGlobalCache: true
packageExtensions:
  "ember-source@*":
    dependencies:
      "@ember/application": "*"
      "@ember/routing": "*"
  "ember-test-helpers@*":
    dependencies:
      "@ember/test-helpers": "*"
